function generate_mex()
    % timeparam: struct with scalar doubles
    timeparam = struct('T', 0, 'dt', 0);

    % localparam
    localparam = struct( ...
        'qmax', zeros(5,1), ...
        'sigma', zeros(5,1), ...
        'theta', zeros(5,1), ...
        'Q0', zeros(5,1), ...
        'V0', zeros(5,1), ...
        'rho', zeros(5,1) ...
    );

    % coupparam
    coupparam = struct( ...
        'nu', zeros(5,5), ...
        'gamma', 0, ...
        'tau', zeros(5,5), ...
        'alpha', 0, ...
        'beta', 0 ...
    );

    connparam = struct( ...
        'C', zeros(200,200), ...
        'tau', zeros(200,200), ...
        'M', int32(0), ...
        'ab', int32(zeros(500, 2)), ...
        'Chet', zeros(500, 1), ...
        'tauhet', zeros(500, 1) ...
    );

    % modparam
    modparam = struct( ...
        'nu', 0, ...
        'Qtonic', 0, ...
        'eta', 0, ...
        'alpha', 0, ...
        'beta', 0, ...
        'rho', 0, ...
        'g', zeros(5,1), ...
        'tau_c', 0, ...
        'tau_t', 0, ...
        'kernel', zeros(1, 200) ...
    );

    % stim
    stim = struct( ...
        'stimnum', int32(1), ...
        'pos', zeros(100, 1), ...
        'sigma', 0, ...
        'stimt', zeros(100,1), ...
        'stimI', zeros(100,1), ...
        'noise', 0, ...
        'seed', 1 ...
    );

    % N_pop and N_nodes
    N_pop = int32(0);
    N_nodes = int32(1);

    % Use codegen to create mex file
    codegen run_model -args {timeparam, localparam, coupparam, connparam, modparam, stim, N_pop, N_nodes} -report
    
end
